### ISSUE TITLE
Usage within FPM

### ISSUE THREAD

**Issue by mpociot** [clue/reactphp-sqlite#35]
I'm using this package in a package of mine, where I need to access the SQLite database within a ReactPHP process, as well as within a standard synchronous request/response lifecycle.
Since I want to reuse the class that holds the database logic, I would like to use this package for both ways.

This is working fine, in general, as I am using your block/await function inside of the synchronous request/response.
The problem with this approach is, that since my web requests are running through `php-fpm`, the `exec` command is using the wrong binary - because `PHP_BINARY` returns FPM.

It would be great to have a setter for the PHP binary so that I could manually overwrite the binary for the synchronous process while maintaining the auto-detection logic within ReactPHP.

Is this something that I should PR?

**Comment by clue** [comment]
@mpociot Thanks for reporting, this actually sounds like both a bug and a new feature candidate!

This project should work when executed from PHP-FPM without requiring any special configuration. We already have a similar code path to avoid launching the CGI binary, so we should probably add similar logic to *never* invoke the PHP-FPM binary. Accordingly, the implementation shouldn't be too hard. Providing a reproducible test case might be more difficult though.

Additionally, it might be useful to provide a way to configure the PHP binary. I consider this to be advanced usage that should be documented as such.

PRs are very much welcome! :shipit:

**Comment by clue** [comment]
@mpociot Good news!

* #50 improves automatic binary detection, so when using CGI/PHP-FPM and it can not find a matching binary, it will now default to `php` instead of reusing the current binary.
* #45 adds support for explicitly passing in a PHP binary path if you need more control over this behavior.
* #48 adds support for explicitly passing in an empty binary path to use a blocking database adapter instead (useful if you're sure you don't need concurrency and/or can't execute a PHP child process at all).

Expect this to be shipped with the next tagged release soon :shipit:
